### ISSUE TITLE
Trying to shift on the wrong side sometimes inserts a lowercase letter

### ISSUE THREAD

**Issue by tiltowait** [tiltowait/Kaleidoscope-BetterShifting#2]
Attempting to type an uppercase letter while hitting the shift key on the same side sometimes prints a lowercase version of that letter.

**Steps to reproduce:**

1. Depress one of the shift keys
1. Depress a non-modifier key on the same side as that shift
1. Release shift
1. Release the non-modifier key

**Observed result:**

A lowercase version of that letter.

**Expected result:**

No letter.

**Reproducibility:** 100%.

**Comment by algernon** [comment]
If you release the non-modifier first (ie, swap steps 3 and 4), does the issue still occur?

**Comment by tiltowait** [comment]
> If you release the non-modifier first (ie, swap steps 3 and 4), does the issue still occur?

No, swapping 3 & 4 does not trigger the bug.

**Comment by algernon** [comment]
In that case, the reason is that with the reproduction steps [this](https://github.com/tiltowait/Kaleidoscope-ProperShifting/blob/d39b987f816c4255e924ff99880bae60f1347a8f/src/Kaleidoscope/ProperShifting.cpp#L93-L97) part of the code will not run, because `left_shift_pressed` (or `right_shift_pressed`) will be false by this point, since you released shift earlier.

The first solution that comes to mind is to change how you [unset shift tracking](https://github.com/tiltowait/Kaleidoscope-ProperShifting/blob/d39b987f816c4255e924ff99880bae60f1347a8f/src/Kaleidoscope/ProperShifting.cpp#L60-L74). Instead of setting `*shift_pressed` to false on `keyToggledOff`, have another set of bool flags, and flip them on if `KeyboardHardware.pressedKeyswitchCount() > 1`. And consume events until this becomes zero. The idea is that you keep the "shift pressed" state until all keys have been released.

**Comment by tiltowait** [comment]
Thanks for the tip. I was able to fix it last night in a7276f752bfa58705af667f601fe592746b20229.
